# Generated by Django 4.0.3 on 2022-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='blog/'),
        ),
    ]
